// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Serraniel and the Sendan contributors

package crypto

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// Tests named TestVectors* are the cross-language contract and are run as their
// own job in continuous integration. They compare this implementation against
// fixtures produced by the other one, rather than against expectations written
// alongside the code they test.

type jsonEncodingVectors struct {
	Description string `json:"description"`
	Spec        string `json:"spec"`
	Generator   string `json:"generator"`
	Cases       []struct {
		Name  string `json:"name"`
		Input struct {
			Name string `json:"name"`
			Type string `json:"type"`
			Size int64  `json:"size"`
		} `json:"input"`
		Expected string `json:"expected"`
	} `json:"cases"`
}

// TestVectorsJSONEncoding checks the deterministic encoder of spec §7.1 against
// output generated by JavaScript's JSON.stringify.
//
// Without this, the Go encoder is only ever compared against expectations
// written by whoever wrote the encoder, which proves nothing about whether the
// browser will produce identical bytes. Since the encoded metadata is
// encrypted, a divergence of one character means a file sealed by the CLI
// cannot be opened by the web client at all.
func TestVectorsJSONEncoding(t *testing.T) {
	path := filepath.Join("..", "..", "testdata", "vectors", "json-encoding.json")
	raw, err := os.ReadFile(path) //nolint:gosec // fixed test fixture path
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}

	var v jsonEncodingVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Cases) == 0 {
		t.Fatal("vector file contains no cases")
	}

	for _, c := range v.Cases {
		t.Run(c.Name, func(t *testing.T) {
			got, err := Metadata{Name: c.Input.Name, Type: c.Input.Type, Size: c.Input.Size}.encode()
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			if string(got) != c.Expected {
				t.Errorf("encoding differs from JavaScript\n  go %q\n  js %q", got, c.Expected)
			}
		})
	}
}
