// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Serraniel and the Sendan contributors

package crypto

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

var updateVectors = flag.Bool("update-vectors", false,
	"regenerate committed vector files; a deliberate act, see the spec on versioning")

// Unlike the JSON encoding vectors, which had to be generated by JavaScript
// because JavaScript was the source of divergence, the content encoding is
// fully determined by the specification given a key and a salt. Go therefore
// acts as the reference producer here, and the TypeScript implementation must
// reproduce these bytes exactly.
//
// Plaintexts are described rather than embedded, so that boundary cases of
// tens of kilobytes do not turn the fixture into a megabyte of hexadecimal.
type contentVectors struct {
	Description string        `json:"description"`
	Spec        string        `json:"spec"`
	Generator   string        `json:"generator"`
	Cases       []contentCase `json:"cases"`
}

type contentCase struct {
	Name string `json:"name"`
	// FileKeyHex and ContentSaltHex are fixed so the output is deterministic.
	FileKeyHex     string `json:"fileKeyHex"`
	ContentSaltHex string `json:"contentSaltHex"`
	// PlaintextLength bytes of PlaintextPattern: "zero" is all 0x00,
	// "counter" is byte i = i mod 256.
	PlaintextLength  int    `json:"plaintextLength"`
	PlaintextPattern string `json:"plaintextPattern"`
	// StreamSHA256 pins the full output. StreamHex is included only for small
	// cases, so the fixture stays readable.
	StreamSHA256 string `json:"streamSha256"`
	StreamHex    string `json:"streamHex,omitempty"`
}

func patternBytes(pattern string, n int) []byte {
	b := make([]byte, n)
	if pattern == "counter" {
		for i := range b {
			b[i] = byte(i % 256)
		}
	}
	return b
}

func buildContentVectors(t *testing.T) contentVectors {
	t.Helper()
	fileKey := bytes.Repeat([]byte{0xA5}, FileKeySize)
	salt := bytes.Repeat([]byte{0x5A}, ContentSaltSize)

	specs := []struct {
		name    string
		length  int
		pattern string
	}{
		{"empty", 0, "zero"},
		{"single byte", 1, "counter"},
		{"short", 100, "counter"},
		{"one byte below a full record", maxRecordPlaintext - 1, "counter"},
		{"exactly one full record", maxRecordPlaintext, "counter"},
		{"one byte above a full record", maxRecordPlaintext + 1, "counter"},
		{"two full records", 2 * maxRecordPlaintext, "counter"},
		{"three records, last partial", 2*maxRecordPlaintext + 12345, "counter"},
	}

	v := contentVectors{
		Description: "Reference output of the spec section 5 content encoding, produced by the Go implementation.",
		Spec:        "docs/spec/wire-format-v1.md section 5",
		Generator:   "go test ./internal/crypto/ -run TestVectorsContentEncoding -update-vectors",
	}

	for _, s := range specs {
		plaintext := patternBytes(s.pattern, s.length)
		var buf bytes.Buffer
		enc, err := newEncryptorWithSalt(&buf, fileKey, salt)
		if err != nil {
			t.Fatalf("%s: new encryptor: %v", s.name, err)
		}
		if _, err := enc.Write(plaintext); err != nil {
			t.Fatalf("%s: write: %v", s.name, err)
		}
		if err := enc.Close(); err != nil {
			t.Fatalf("%s: close: %v", s.name, err)
		}

		stream := buf.Bytes()
		sum := sha256.Sum256(stream)
		c := contentCase{
			Name:             s.name,
			FileKeyHex:       hex.EncodeToString(fileKey),
			ContentSaltHex:   hex.EncodeToString(salt),
			PlaintextLength:  s.length,
			PlaintextPattern: s.pattern,
			StreamSHA256:     hex.EncodeToString(sum[:]),
		}
		if s.length <= 256 {
			c.StreamHex = hex.EncodeToString(stream)
		}
		v.Cases = append(v.Cases, c)
	}
	return v
}

// TestVectorsContentEncoding pins the byte-level output of the content
// encoding. A change here is a wire format change: existing links would stop
// opening, so it requires a new specification version rather than a refreshed
// fixture.
func TestVectorsContentEncoding(t *testing.T) {
	path := filepath.Join("..", "..", "testdata", "vectors", "content-encoding.json")
	generated := buildContentVectors(t)

	if *updateVectors {
		out, err := json.MarshalIndent(generated, "", "  ")
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil { //nolint:gosec // fixture, not a secret
			t.Fatalf("write vectors: %v", err)
		}
		t.Logf("regenerated %d cases in %s", len(generated.Cases), path)
		return
	}

	raw, err := os.ReadFile(path) //nolint:gosec // fixed test fixture path
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var committed contentVectors
	if err := json.Unmarshal(raw, &committed); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(committed.Cases) != len(generated.Cases) {
		t.Fatalf("committed vectors have %d cases, generated %d", len(committed.Cases), len(generated.Cases))
	}

	for i, want := range committed.Cases {
		got := generated.Cases[i]
		t.Run(want.Name, func(t *testing.T) {
			if got.StreamSHA256 != want.StreamSHA256 {
				t.Errorf("stream digest changed\n  got  %s\n  want %s", got.StreamSHA256, want.StreamSHA256)
			}
			if want.StreamHex != "" && got.StreamHex != want.StreamHex {
				t.Errorf("stream bytes changed\n  got  %s\n  want %s", got.StreamHex, want.StreamHex)
			}
		})
	}
}

// The fixture must also decrypt, so it pins a stream that is actually valid
// rather than merely one this implementation happens to reproduce.
func TestVectorsContentEncodingDecrypts(t *testing.T) {
	path := filepath.Join("..", "..", "testdata", "vectors", "content-encoding.json")
	raw, err := os.ReadFile(path) //nolint:gosec // fixed test fixture path
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v contentVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}

	for _, c := range v.Cases {
		if c.StreamHex == "" {
			continue
		}
		t.Run(c.Name, func(t *testing.T) {
			fileKey, err := hex.DecodeString(c.FileKeyHex)
			if err != nil {
				t.Fatalf("decode key: %v", err)
			}
			stream, err := hex.DecodeString(c.StreamHex)
			if err != nil {
				t.Fatalf("decode stream: %v", err)
			}
			got, err := open(t, fileKey, stream)
			if err != nil {
				t.Fatalf("decrypt: %v", err)
			}
			want := patternBytes(c.PlaintextPattern, c.PlaintextLength)
			if !bytes.Equal(got, want) {
				t.Fatal("decrypted content does not match the described plaintext")
			}
		})
	}
}

// The declared length is pinned to the shared vectors, not only to this
// implementation's encoder.
//
// A browser and the command line client uploading the same file must declare
// the same number: the instance enforces the declaration, so two clients that
// disagreed would mean one of them could never complete an upload. Both
// implementations compute this, and the vector already carries the answer -
// each case states a plaintext length and the stream it produces.
func TestVectorsEncodedContentLength(t *testing.T) {
	path := filepath.Join("..", "..", "testdata", "vectors", "content-encoding.json")
	raw, err := os.ReadFile(path) //nolint:gosec // fixed test fixture path
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v contentVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}

	checked := 0
	for _, c := range v.Cases {
		if c.StreamHex == "" {
			continue
		}
		stream, err := hex.DecodeString(c.StreamHex)
		if err != nil {
			t.Fatalf("%s: stream: %v", c.Name, err)
		}

		got, err := EncodedContentLength(int64(c.PlaintextLength))
		if err != nil {
			t.Fatalf("%s: %v", c.Name, err)
		}
		if got != int64(len(stream)) {
			t.Errorf("%s: plaintext of %d bytes declared %d, the vector's stream is %d",
				c.Name, c.PlaintextLength, got, len(stream))
		}
		checked++
	}

	if checked == 0 {
		t.Fatal("no vector carried a stream, so nothing was compared")
	}
}
