// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Serraniel and the Sendan contributors

/**
 * Rendering the changelog.
 *
 * The file is generated by release-please, so its Markdown is a narrow, known
 * subset: headings, list items, bold runs, inline code and links. Nothing else
 * appears in it, and anything else that does appear is shown as text rather
 * than interpreted.
 *
 * ## Why not a Markdown library
 *
 * The general ones are tens of kilobytes for four constructs, and add a licence
 * whose notice has to travel with the bundle. The tiny ones pass raw HTML
 * straight through, so they would need a sanitiser, which is larger than this.
 *
 * ## Escaping comes first
 *
 * Every line is escaped before any construct is applied, so a `<` in a commit
 * message is a `<` on the page and never the start of an element. The policy
 * forbids inline scripts and handlers as well, but that is the second line of
 * defence rather than the first: a page that depends on a header being present
 * is a page that breaks wherever it is not.
 */

/** One rendered block, in the order it should appear. */
export type Block =
  | { kind: "heading"; level: 1 | 2 | 3; html: string }
  | { kind: "list"; items: string[] }
  | { kind: "paragraph"; html: string };

/** A link found in the source, so the page can decide how to present it. */
export interface Link {
  href: string;
  text: string;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Whether a link may be rendered as one.
 *
 * Only http and https. A generated changelog contains nothing else, and
 * refusing the rest keeps `javascript:` out by construction rather than by
 * remembering to check for it - relative links included, since there is nothing
 * in this file for one to point at.
 */
function isSafeHref(href: string): boolean {
  return /^https?:\/\//i.test(href);
}

/**
 * Inline constructs, applied to already-escaped text.
 *
 * Links first: their text may contain the others, and running bold over a URL
 * would corrupt it.
 */
function inline(escaped: string): string {
  let out = escaped.replace(/\[([^\]]*)\]\(([^)\s]+)\)/g, (whole, text: string, href: string) => {
    // The href arrives escaped, so &amp; has to come back before it is a URL
    // again. Only ampersands: nothing else in a URL was altered.
    const url = href.replace(/&amp;/g, "&");
    if (!isSafeHref(url)) return whole;
    return `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${text}</a>`;
  });

  out = out.replace(/`([^`]+)`/g, "<code>$1</code>");
  // Bold last, and non-greedy, so `**a** and **b**` is two runs rather than one
  // spanning the middle.
  out = out.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  return out;
}

/**
 * Turns the changelog into blocks.
 *
 * Blocks rather than one string of HTML: the page decides how each is
 * presented, and a test can assert structure instead of matching markup.
 */
export function render(markdown: string): Block[] {
  const blocks: Block[] = [];
  let items: string[] = [];

  const flush = () => {
    if (items.length > 0) {
      blocks.push({ kind: "list", items });
      items = [];
    }
  };

  for (const raw of markdown.split(/\r?\n/)) {
    const line = raw.trimEnd();

    if (line.trim() === "") {
      flush();
      continue;
    }

    const heading = /^(#{1,3})\s+(.*)$/.exec(line);
    if (heading !== null) {
      const [, hashes = "", text = ""] = heading;
      flush();
      blocks.push({
        kind: "heading",
        level: hashes.length as 1 | 2 | 3,
        html: inline(escapeHtml(text)),
      });
      continue;
    }

    const item = /^\s*[*-]\s+(.*)$/.exec(line);
    if (item !== null) {
      const [, text = ""] = item;
      items.push(inline(escapeHtml(text)));
      continue;
    }

    flush();
    blocks.push({ kind: "paragraph", html: inline(escapeHtml(line)) });
  }

  flush();
  return blocks;
}
